### ISSUE TITLE
Joint genotyping: MakeSitesOnlyVcf jobs failing in seqr load pipeline.

### ISSUE THREAD

**Issue by cassimons** [populationgenomics/production-pipelines#282]
All jobs are failing with the following error message (eg [job](https://batch.hail.populationgenomics.org.au/batches/421086/jobs/5) [batch](https://batch.hail.populationgenomics.org.au/batches/421086?q=failed)). I have not investigated if the issue is here or in the upstream ExcessHet_filter job.

```+ gatk --java-options -Xms6500m MakeSitesOnlyVcf -I /io/batch/7c9719/ExcessHet_filter-U4Q7I/output_vcf -O /io/batch/7c9719/MakeSitesOnlyVcf-tOO8D/output_vcf.vcf.gz
Using GATK jar /root/micromamba/share/gatk4-4.2.6.1-1/gatk-package-4.2.6.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms6500m -jar /root/micromamba/share/gatk4-4.2.6.1-1/gatk-package-4.2.6.1-local.jar MakeSitesOnlyVcf -I /io/batch/7c9719/ExcessHet_filter-U4Q7I/output_vcf -O /io/batch/7c9719/MakeSitesOnlyVcf-tOO8D/output_vcf.vcf.gz
09:24:06.546 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/root/micromamba/share/gatk4-4.2.6.1-1/gatk-package-4.2.6.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Sun Feb 05 09:24:06 UTC 2023] MakeSitesOnlyVcf --INPUT /io/batch/7c9719/ExcessHet_filter-U4Q7I/output_vcf --OUTPUT /io/batch/7c9719/MakeSitesOnlyVcf-tOO8D/output_vcf.vcf.gz --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX true --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Sun Feb 05 09:24:06 UTC 2023] Executing as root@hostname-75e756c7b3 on Linux 5.13.0-1021-gcp amd64; OpenJDK 64-Bit Server VM 11.0.15-internal+0-adhoc..src; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.2.6.1
[Sun Feb 05 09:24:06 UTC 2023] picard.vcf.MakeSitesOnlyVcf done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=6588596224
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
htsjdk.samtools.SAMException: Cannot read non-existent file: file:///io/batch/7c9719/ExcessHet_filter-U4Q7I/output_vcf
	at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:498)
	at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:485)
	at picard.vcf.MakeSitesOnlyVcf.doWork(MakeSitesOnlyVcf.java:85)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:37)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)```

**Comment by MattWellie** [comment]
FYI @cassimons @vivbak I think this is a weird error that's been inserted into the cpg-workflows codebase, and I couldn't work out how this could be right. I pulled my hair out for a while, then removed this step from AIP, on the basis that it must work in the pipeline, and I wasn't gonna change the pipeline codebase just for my needs 😬 

[Offending line](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/jobs/joint_genotyping.py#L501)

The input VCF for this job tracks back to [this line](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/jobs/joint_genotyping.py#L438)


So in the command, we're copying in a resource group (VCF and TBI), referencing the resource group rather than the specific file, so the command to GATK has no file extension

**Comment by cassimons** [comment]
@MattWellie, so that line just needs to change to ` -I {input_vcf['vcf.gz']}`?

**Comment by vivbak** [comment]
So strange that this is the first time this has come up? Awesome find @MattWellie! Yeah, you can see an example of how these ResourceGroups should be called here https://github.com/populationgenomics/production-pipelines/blob/175e8ed27dfb33c432d9aecd01d9c72c6ab41ac4/cpg_workflows/jobs/happy.py#L45 

I'm checking in on if I've missed any context from the last seqr meeting, but I will go ahead and see if this was missed anywhere else in the codebase also.

**Comment by cassimons** [comment]
Thanks @vivbak :-) 

I dont think there was anything unusual about this run so no idea why it was not surfaced before?

**Comment by MattWellie** [comment]
I think this turned up in cpg-workflows after 1.4.1, is it be possible that pipeline runs have been set off using a cpg-workflows version prior to that?

**Comment by vivbak** [comment]
This should hopefully be fixed now :) Please let me know if you're able to run successfully or if you encounter the same issue again.

**Comment by cassimons** [comment]
Thanks Vivian. Those jobs seem to be working now which is great. Thanks for your help with this.
