### ISSUE TITLE
Somalier extract jobs producing empty output

### ISSUE THREAD

**Issue by cassimons** [populationgenomics/production-pipelines#283]
When running the seqr loading pipeline, all Somalier extract jobs appear to produce a valid Somalier output file that incorrectly reports 0 coverage for the sample.

The impact of this can be seen [here](https://main-web.populationgenomics.org.au/udn-aus/qc/cram/multiqc.html) - all samples have good coverage as reported by picard, but Somalier is reporting 0 coverage.

Looking at an individual[ Somalier extract job](https://batch.hail.populationgenomics.org.au/batches/420926/jobs/12506), it looks to have run to success and produced an output file. However, these files are consistently 17bytes whereas a functional output file should be much larger than that.

**Comment by vivbak** [comment]
Hi @cassimons do you know if this same issue has been reproduced in -test?

**Comment by cassimons** [comment]
No sorry, I only ran into it yesterday in prod. Thank you for pushing that fix!CSent from my iPhoneOn 6 Feb 2023, at 2:21 pm, Vivian Bakiris ***@***.***> wrote:﻿
Hi @cassimons do you know if this same issue has been reproduced in -test?

**Comment by cassimons** [comment]
Sorry, getting my threads mixed up. I think Vlad and I found the Somalier issue just before Xmas. I need to check but I do not think I had time to try it in test, will have a look tonight. CSent from my iPhoneOn 6 Feb 2023, at 2:21 pm, Vivian Bakiris ***@***.***> wrote:﻿
Hi @cassimons do you know if this same issue has been reproduced in -test?

**Comment by lgruen** [comment]
I've attached a list of affected CRAMs. It spans across the following datasets: `broad-rgp`, `hereditary-neuro`, `ibmdx`, `perth-neuro`, `prophecy`, `udn-aus`, and `validation`.
[somalier.txt](https://github.com/populationgenomics/production-pipelines/files/10799756/somalier.txt)
