### ISSUE TITLE
Add UTRAnnotator to VEP

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/production-pipelines#304]
https://github.com/ImperialCardioGenetics/UTRannotator

VEP plugin to annotate high-impact five prime UTR variants either creating new upstream ORFs or disrupting existing upstream ORFs.

Check out whether this would be a simple addition to the standard VEP image/deployment, or whether we can make a non-standard VEP image with this included

**Comment by cassimons** [comment]
This would be really good to have if it did not break other things  ✅

**Comment by MattWellie** [comment]
Pros: the plugin seems to only need a few files added and no huge data file(s)
Cons: the plugin (according to its own README) doesn't currently support JSON VEP output, which is the format required in the VEP -> MT pipeline stage

**Comment by vivbak** [comment]
//Current Assessment: Not on 9 month plan, lack of viability. We can re-open down the track if things change. 
CC @MattWellie
