### ISSUE TITLE
Determine the set of sites to use for contamination detection with VerifyBamID

### ISSUE THREAD

**Issue by KatalinaBobowik** [populationgenomics/production-pipelines#327]
VerifyBamID currently uses a set of [contamination sites](https://github.com/populationgenomics/production-pipelines/blob/288e9a06087cf979cf0c4a75e121a05f5ce72064/cpg_workflows/jobs/verifybamid.py#L40-L42) in line with the Broad's WARP pipeline. 

We need to confirm how these sites were selected, and that they are appropriate for use with the diverse OurDNA cohorts.

**Comment by KatalinaBobowik** [comment]
I'm a bit confused on where these tables are actually coming from. The `reference_path()` command should be pulling these files from the input config, under the `[references.broad]` section, however I can't find that in any of the configs. I feel like this should break if there's no file provided, so maybe I'm misunderstanding something.

Vivian did point to a references table, located [here](https://github.com/populationgenomics/references/blob/4a5cd49989e90e35edf7564b4c713d124bcf8cc6/references.py#L75), which lists these files.

**Comment by katiedelange** [comment]
So our interpretation here is that `reference_path()` is using a .toml created in the analysis-runner environment (as per the [README](https://github.com/populationgenomics/references/blob/2978fd246cac30091b7459843a2e2561ebbabdca/README.md) and [this code](https://github.com/populationgenomics/references/blob/0435cd44478fd997b7d2500c7913cf38c88e6982/.github/workflows/prep_config.py)), which is loaded in before (and therefore as lower priority) that the large cohorts config and any dataset specific configs.

This means that, provided no `[references.broad]` section is provided in the dataset or large cohorts configs, the version in the references table Kat linked above will be used.

**Comment by katiedelange** [comment]
The references toml is created/updated using CI whenever a commit is merged into the main branch of the references repo, meaning that the [latest version of references on main](https://github.com/populationgenomics/references/blob/main/references.py#L111-L117) will be the files used.

**Comment by KatalinaBobowik** [comment]
As far as the selection of sites goes, a README is located in the [gcp-public-data--broad-references](https://console.cloud.google.com/storage/browser/gcp-public-data--broad-references/hg38/v0/contamination-resources/1000g?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) bucket and can be found [here](https://ff29435f1377d99d6c7b122e6b59aa4619c2d054aff61b92939ecbe-apidata.googleusercontent.com/download/storage/v1/b/gcp-public-data--broad-references/o/hg38%2Fv0%2Fcontamination-resources%2F1000g%2FREADME_1000G_EXOME_CONTAMINATION.TXT?jk=AahUMluLUr-3Kmj4wsInzJdLZt1vfYLPgCT5oNBSsJWxrArLCLaam8416Th-8Gpc4wwr5Bh7Fvpkt8HF5ONaF9RwySGVE_5j5o_iqNq_NzUMrv_JyZrMojtWqCI5bUCqnGVSM9_sYdLyZFRM-lu4Jrbenvf8wOWwPOGTgWolqKproJqN2bjJ-hgJsn3kqtCK8YkCDjIo7G9LH3YulAWQQ4kRBoRV5T_zRp2tE9I9gIUwjL9gSO9gwrg06NG6kq3Xkvt1o7ckc0ec1YglosPGy0fbA0c0O-NIQSPgZCqYlkG8JkYmo2jDNdRQXEwAZiX-B2l0825EQNr-29fCrB4rp76z4g42PrNc7awxDY6HwiC0-R0vEaIJVcAwZSB2R8_ew1_LGY0ZKgd0Rt6fawUb9XVU5joWy4LkwwNY75qsfnjbkJNaOVfjG708mUHlf2p41SX4pCLAFY1_tMdMe8lobdy6AXe1rPRKdehL6uSvJ6vcveM9NEDzeKmh74ic6Tw39ik9PYbnYwuCytm3aVhEITsktbj9c54AYvdad1AYupW-B_njZjEPILxVX4WyqjqsrqpFjywTe863h2uC47xhQntSbmq5gnH6ovRWO8GjFwMcxaKnmNSj07r3GD8DeqWg-b3kr991sQtu9HPtdQEW8gvfXQQU-UpYBhwPzBMHG48AXKTA_xBrJavOjmcEoWGSsCsiqFm_tedQgmrutnJa9SiA93CtmXlRZkzN3g2xLKIipUNfQuvV6eOlfKczEGRdJ2bgQS0Jjg09fgusslwuBZtgALgfZ0m36HYqmLfN0SUh7wDpuSjSAymFAwzAoQVf_eNj0gFd8UsxWrakqkHk5Ie1z-RbP_E2zAo1-BsNzta6NtOC09veFwg3TzO5LONDqMbM069QWq7feHY2mefFBUbX7tx4TkFvROkTooacNI5l0kGk8AG7ilMsuWS1TXoRMlXt_iyh6Il8n50t41MdW0T85iZqmrkaY2VkUgv_7D9eIzEnNrsUD0wUW5gV57jwTt7984M49rvwGExtUhHzIYb2qZXm348Wk7co5XlzI_gzmJbdbLFdbop6F2-S7KsH6SNZT31Dg1fl7eK3RiQuT-Fp6apnVjN4N2mq-mnVOVIDMtprLLba9gboCqLEqjDXU_hfLTAakVpYAtFhovQTnj2mqXJGr7ODHoq5VrllwnOtWx0jlOh51n0KNrNODhXJVjWdQZTxiGCMqoQbSzH-AeTWSadBZ32zHBwA2P6M4E9420lFLAV4X8GHcH_b6_SxSX-H_eoDPRFNRTs3tdwsfkweppHhLSQHouxASNWgt0Ce6i9RKTXjrA&isca=1).

Given that this data is created from the 1000 genomes project and is ancestry-agnostic to estimating DNA contamination, it seems like a good reference for our purposes.

**Comment by vivbak** [comment]
I believe this issue can be closed now. But please feel free to re-open if that's not accurate!
