### ISSUE TITLE
Check that first_ and last_stages are always forced

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/production-pipelines#362]
The GATK-SV workflow requires running as a couple of sub-workflows. Until we have funky custom cohorts/datasets, we'd like to just check that running the pipeline with first and/or last stages is a hard restriction

**Comment by daniaki** [comment]
Just so I am understanding - raise an error unless `first_stages` and `last_stages` are defined? How about either those or `only_stages` too?

**Comment by MattWellie** [comment]
@daniaki sorry, this was a bit of a placeholder issue. We just wanted to make sure that the config settings for first/last_stages did do what they were supposed to. I think that's been confirmed, so I'm happy to close it
