### ISSUE TITLE
Only_Stages still checks output of other stages

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/production-pipelines#371]
I was being a little naive maybe, and expected that listing a stage in config under only_stages would run and check that stage exclusively, e.g. https://batch.hail.populationgenomics.org.au/batches/424485/jobs/1

Here the config contained:

```
only_stages = ['DatasetVCF']
```

The job failed because the output of `MtToEs` was not created. MtToEs is a separate leaf node to DatasetVCF, so it shouldn't really have been considered. I managed to get the behaviour I expected by combining:

```
first_stages = ['DatasetVCF']
last_stages = ['DatasetVCF']
only_stages = ['DatasetVCF']
```

Can we update the workflow graph assessment to treat `only_stages` as a combination of `first_stages` and `last_stages`, i.e. don't consider any inputs/outputs other than ones immediately relevant to the ones listed in `only_stages`. I've not looked at this in great detail, and there is a workaround. If there's a combination of `check_inputs`, `check_intermediates`, and `check_expected_outputs` which creates an equivalent behaviour that would be grand too.

*related side note, the MtToEs `.done` file looks like the only one in our pipeline which contains a full timestamp in the name. It can be overridden, but is there a reason we are treating it differently to all other naming conventions? There almost certainly is, this is just an observation 🙃

**Comment by daniaki** [comment]
Seems like handling `only_stages` hasn't been properly implemented yet in the `Workflow` class. If you still need it, here's a quick workaround that might work:

`allow_missing_outputs_for_stages = ['MtToEs', ...]`

I've got a working solution that I'll get you to review shortly.
