### ISSUE TITLE
Add a retry mechanism to metamist network calls

### ISSUE THREAD

**Issue by daniaki** [populationgenomics/production-pipelines#411]
There have been some bugs where a metamist API call fails but might have succeeded if retried. A retry function decorator with the signature:

```python
@retry(n_retries: int = 5, delay_in_seconds: int = 3, backoff: Literal['exponential' | 'constant'] = 'exponential')
```

Would be easy to add to existing class methods without changing each block of code.

**Comment by vivbak** [comment]
Duplicated in https://github.com/populationgenomics/production-pipelines/issues/585
