### ISSUE TITLE
VEP schema decoding is causing silent failures

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/production-pipelines#486]
## Context 

Our annotation pipeline follows this process:
1. Split a VCF into multiple VCF fragments (code link)
2. Annotate each fragment with VEP, producing a JSON output ([code link](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/jobs/vep.py#L189))
3. Read the many JSON fragments back into a single Hail Table ([code link](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/query_modules/vep.py))

Inferring type and data structure while ingesting JSON is incredibly inefficient, so we process using a [fixed schema](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/query_modules/vep.py#L15). 

## Issue

The schema we are using is incomplete, but we never found out because of a silent failure mode

## Examples

From a [recent batch](https://batch.hail.populationgenomics.org.au/batches/429011/jobs/101) - this is the Job which collates all the VEP JSON into a Hail Table. Note that the logs here are completely free of issues ☮️ 

As we are using Query on Batch, each of the tasks is carried out as a separate process - Batch ID https://batch.hail.populationgenomics.org.au/batches/429013

[Example job](https://batch.hail.populationgenomics.org.au/batches/429013/jobs/73)

This worker job contains a number of parsing errors due to missing

[Earlier example](https://batch.hail.populationgenomics.org.au/batches/427975/jobs/8413) (completely separate from latest VEP updates) and a corresponding [worker task](https://batch.hail.populationgenomics.org.au/batches/427976/jobs/15) with errors

e.g.
```
<schema> has no field uniprot_isoform at <root>.transcript_consequences[element] for value JArray(List(JString(Q96S66-3)))
<schema> has no field seq_region_name at <root>.colocated_variants[element] for value JString(1)
```

## Conclusion?

I don't think this is urgent - the fields being missed out aren't processed during AnnotateCohort, so they don't end up in Seqr - impact here is minimal

We should be aware of this potential silent failure in future, and address schema discrepancies where appropriate

## Resolution

- Update VEP 105 schema to resolve these issues
- Update/design VEP 110 schema to avoid issues

**Comment by vivbak** [comment]
Nothing left to action CC @MattWellie :)
