### ISSUE TITLE
Unexpected Cross-Batch Behavior in Hail Batch: Shared Sequencing Group IDs Between Batches Leading to Job Failures

### ISSUE THREAD

**Issue by michael-harper** [populationgenomics/production-pipelines#532]
A Hail Batch ([#1](https://batch.hail.populationgenomics.org.au/batches/430116)) submission of 100 sequencing groups failed at MultiQC [CRAM] and MultiQC [GVCF]. 

The output of the jobs that failed indicate input files don't exist. The sequencing group prefixes of these input files however are not the sequencing groups submitted in the Batch's config file. They are from a secondary batch of 100 ([#2](https://batch.hail.populationgenomics.org.au/batches/430183)) sequencing groups submitted as the initial batch of 100 was nearing completion. 

As batch `#2` was progressing, the missing files were being generated and thus came into existence. Nonetheless, this does not explain why batch `#1` was looking for files related to sequencing groups from a completely separate batch with no overlapping sequencing groups.

**Comment by MattWellie** [comment]
Feels simple enough - the files which are used to work out which files are eventually required are written before the batch starts [here](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/jobs/multiqc.py#L64-L66) e.g. `gs://cpg-bioheart-main-tmp/multiqc/cram/multiqc-file-list.txt`  - i.e. the second batch overwrote this location as it was starting, which lead to the first batch reading the updated version. This path should probably be edited to include something specific to the batch in the file path (e.g. the output prefix containing the hash of the specific group of sample IDs)

**Comment by MattWellie** [comment]
Specifically - the file is written before the batch starts, but the file is only read into the batch during the input phase of the exact job that requires it (https://batch.hail.populationgenomics.org.au/batches/430116/jobs/6650). By the time the file is read into the batch, the contents have been overwritten
