### ISSUE TITLE
Detection of PCR+/- is total Nonsense

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/production-pipelines#575]
I'm pretty sure that when I first wrote this, it was based on content I was seeing in Metamist results. Not the `pcr_status` attribute is nowhere to be seen, not sure if I completely imagined it.

Is there any top-level attribute on sequencing groups or assays to determine whether the reads were generated using PCR, without digging into specific library preparations by name etc.

https://github.com/populationgenomics/production-pipelines/blob/de88e8af7bd54be82e3b34ce567e9de1bda7a5a4/cpg_workflows/stages/gatk_sv/gatk_sv_single_sample.py#L281-L292

**Comment by vivbak** [comment]
The fix here sits in Data Management, and outside of Production Pipelines. Not sure if there's place for these issues 
@EddieLF FYI
CC @MattWellie 

Closing for now, but should be re-opened elsewhere :) <3
