### ISSUE TITLE
BCFTools and BATCH_TMPDIR

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/production-pipelines#584]
https://github.com/populationgenomics/production-pipelines/blob/e02782bddc943f1402a7827f781aee0a209af716/cpg_workflows/jobs/vcf.py#L176

Based on @hopedisastro's experiments, bcftools doesn't add a slash here when using as a temp directory
https://batch.hail.populationgenomics.org.au/batches/431549/jobs/1

```
hail batch env variable:
{
    "name": "BATCH_TMPDIR",
    "value": "/io/batch/bdcc1f"
}

command:
bcftools sort --temp-dir $BATCH_TMPDIR 

outputs:
buf_flush] Error: cannot write to /io/batch/bdcc1fWyLxsI/00003.bcf
```

I'm not sure if this is meaningful, but the temp path used isn't nested inside BATCH_TMPDIR, but is instead created at the same level. If it ain't broke, don't fix it, but I'm just flagging this here.

This would be corrected by using `--temp-dir ${BATCH_TMPDIR}/`

**Comment by vivbak** [comment]
Closing for now, we can consider re-opening if it creates issues down the track. At the moment we can flag this as a 'known behaviour'. 

Unless anyone actually wants the fix

CC @MattWellie
