### ISSUE TITLE
[gatk-sv] GATK-SV

### ISSUE THREAD

**Issue by vladsavelyev** [populationgenomics/production-pipelines#6]
- [x] Run GatherSampleEvidence on one sample.
- [x] GatherSampleEvidence: figure out the runtime for one full genome sample, and how individual callers contribute to it.
- [x] Update our branch from the upstream.
- [x] Python script to update docker images
- [ ] Run TrainGCNV.
- [ ] Run full workflow to the completion on 2 or 3 trios.
- [ ] Design pipeline with `cpg-pipes` and python cromwell analysis-runner helper.

**Comment by vivbak** [comment]
Updated from Upstream: https://github.com/populationgenomics/gatk-sv/pull/3
