### ISSUE TITLE
GCP Housekeeping jobs?

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/production-pipelines#617]
We have a number of jobs which nominate a temporary data directory, and write potentially huge amounts of data to them (e.g. AnnotateCohort which generates multiple checkpoints, or GATK-SV in general which is a storage-hungry beast).

I would like to consider follow-on jobs which would run if the main job completes successfully, clearing the temporary storage directory which was used.

We'd need to poke the numbers, and see if this is worth the effort.

**Comment by vivbak** [comment]
> We'd need to poke the numbers, and see if this is worth the effort.
I agree with this. I'm scared of deleting things in the pipeline :) 

Tag this under: Investigate?

**Comment by vivbak** [comment]
Also tag this under cost optimisation

**Comment by MattWellie** [comment]
I don't think the financial hit we're taking by storing some stuff in temp here is fatal to the business, and we can happily resolve most of this by writing data to temp and letting that data lifecycle play out.

With our current permissions setup, we'd need to run everything (including these sweeping deletions) with full permissions, and that's a behaviour we'd like to move away from
