### ISSUE TITLE
Remove all GATK-SV QC/Metrics sub-workflows

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/production-pipelines#689]
GATK-SV is run using a few top-level WDL files, each of which calls a number of sub-workflows. Many of those workflows which are on by default are not required for production running (QC plots, summary metric file generations).

Once we've obtained some plots, we should deactivate all these workflows which aren't required to generate SV results. We can access these switches through config, so turn them all off in the default config. We can still override the setting to reactivate using config. These are the accessible switches we should set to false (not run):

(see https://github.com/search?q=repo%3Abroadinstitute%2Fgatk-sv+if+%28run_module&type=code)

## SingleSample

- [GatherSampleEvidence](https://github.com/broadinstitute/gatk-sv/blob/d37e453038e425acba9683da503218fe3d4b1033/wdl/GatherSampleEvidence.wdl#L274)

## MultiSample1

- [GatherBatchEvidence](https://github.com/broadinstitute/gatk-sv/blob/d37e453038e425acba9683da503218fe3d4b1033/wdl/GatherBatchEvidence.wdl#L131)
- [ClusterBatch](https://github.com/broadinstitute/gatk-sv/blob/d37e453038e425acba9683da503218fe3d4b1033/wdl/ClusterBatch.wdl#L57)
- [GenerateBatchMetrics](https://github.com/broadinstitute/gatk-sv/blob/d37e453038e425acba9683da503218fe3d4b1033/wdl/GenerateBatchMetrics.wdl#L43)
- [FilterBatch](https://github.com/broadinstitute/gatk-sv/blob/main/wdl/FilterBatch.wdl#L25)
- [GenotypeBatch](https://github.com/broadinstitute/gatk-sv/blob/d37e453038e425acba9683da503218fe3d4b1033/wdl/GenotypeBatch.wdl#L44)

## MultiSample2

- [MakeCohortVcf](https://github.com/broadinstitute/gatk-sv/blob/main/wdl/MakeCohortVcf.wdl#L71) (also addresses [CleanVcf](https://github.com/broadinstitute/gatk-sv/blob/d37e453038e425acba9683da503218fe3d4b1033/wdl/CleanVcf.wdl#L37))
- [FilterGenotypes](https://github.com/broadinstitute/gatk-sv/blob/main/wdl/FilterGenotypes.wdl#L34)

**Comment by cassimons** [comment]
Sounds good.  In the Config can we include a sentence summary of what (we think) each workflow does? The names are not great to guess this for.

**Comment by MattWellie** [comment]
I can't wait to see how much overall runtime (and potentially cost) this saves us.
