### ISSUE TITLE
Kill Cromwell resource hogs

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/production-pipelines#702]
The shiny new billing interface has made it really simple to track per-sample costs in a multi-sample Cromwell workflow. Specifically we can see that some of the samples which continue on for multiple days are costing ~100x as much as a clean sample completion. 

These long running samples rarely complete at all, and if we'd had this clarity before we'd have killed runs much more readily.

Can we set a timeout for jobs/stages in Cromwell, so that if the stage runs over a set limit (e.g. 24h) the job is automatically killed on the Cromwell side?

Alternatively if that's not trivial, would it be easy to update the Watch task to take a max_duration argument, posting an abort signal for the workflow if the limit is passed?

Happy to action this, but I wanted to try and crowdsource whether cromwell has an easy time-to-kill solution as I can't find one in the documentation, and for GATK-SV editing the actual WDL files is non-trivial

**Comment by illusional** [comment]
As far as I know, no from WDL and [Cromwell](https://cromwell.readthedocs.io/en/stable/RuntimeAttributes/). I'd also stay away from using the preemptible flag to do this.

You could try asking on the Cromwell slack to see if anyone else has got a solution, but it's fairly quiet.

**Comment by MattWellie** [comment]
Thanks, I've asked there, but will try and cook up a PR to solve internally in case they confirm that nothing easy exists

**Comment by MattWellie** [comment]
This is hopefully closed by https://github.com/populationgenomics/cpg-utils/pull/165
