### ISSUE TITLE
RecursionError when submitting cpg_workflows pipeline runs

### ISSUE THREAD

**Issue by vivbak** [populationgenomics/production-pipelines#775]
Failing batch link: 
https://batch.hail.populationgenomics.org.au/batches/454658/jobs/1

Can be repro'd with the following launch.json
```
{
    "name": "SEQR loader",
	"type": "debugpy",
	"request": "launch",
	"program": "${workspaceFolder}/main.py",
	"justMyCode": false,
	"args": [
	    "seqr_loader"
	],
	"python": "path_to_python",
	"console": "integratedTerminal",
	"env": {
	    "SM_ENVIRONMENT": "",
	    "CPG_CONFIG_PATH": "gs://path_to_config_from_failed_batch",
	    "PYTHONPATH": "${workspaceFolder}/seqr-loading-pipelines"
	}
}
```

Seems to be a pickling issue, though the latest attempt at resolving has not resolved the issue 
https://github.com/populationgenomics/production-pipelines/pull/772 

First reported by @EddieLF

**Comment by MattWellie** [comment]
@vivbak can this be closed now?
