### ISSUE TITLE
[production-pipelines] Transition to DRAGMAP

### ISSUE THREAD

**Issue by vladsaveliev** [populationgenomics/production-pipelines#8]
Illumina will sponsor reprocessing gnomAD samples, so we will have to transition to DRAGMAP as well.

Need to figure out issues with DRAGMAP:

- [ ] Reading from stdin to support BAZAM: https://github.com/Illumina/DRAGMAP/issues/24
- [ ] From Picard MarkDup: ERROR::INVALID_CIGAR:Read name ERR194147.89269908, No real operator (M|I|D|N) in CIGAR https://batch.hail.populationgenomics.org.au/batches/7381/jobs/3

Alternative solution would be to use BWA with alts mask. From Michael Gatzen:
> With regards to using a BWA mem with the masked reference, this is supported in our recent WARP pipeline release, by selecting use_bwa_mem=true and using the reference files in gs://gcp-public-data--broad-references/hg38/v0/dragen_reference

**Comment by EugeneEA** [comment]
@vladsavelyev Hi, did you solve that problem by any chance?
Best, Eugene
